language: go

go:
- '1.14'

install:
- go mod download

script:
- go build -o semver

deploy:
  provider: releases
  api_key:
    secure: LVsuLiJwBQjTZ401AkYZb6plsaUorBcngk71jVKJfvqeQ5gbkKjhxyzq1cpU7zoOuxaHaDRLnpT17kEZ2bvFILSV/2Q+NXqjYLd/PjvRSYPVKF7/TQVZUF9tScZI4v18GLytbB8WSWQJ3StBHTKpMQzulfNpH7UXRZSejvwYdMFibg16rGfoUBihikrExI/STpBEYWt3i/HREQrLVI4t/r9K6KlN+eQiYefXkf14zRv+6sW7KgW71ix9h8H1drGyQPI8jNm0YhXQ/wY83rgqY7sQXXnQaRRmKj2hc1vN5yRfkv7ijDpA6Lbzo87jXK7AnjQHAKZTtTF396bsNk3YAf6Qx6qehLIhwvsBJzuoel8e2qG1oNhrlJXCcv1gVfaKG/t7dk1Gs9oZyNe4Tn3tBg1O4WfYPdcOnSUSF/3ABFqkdUqm2/9tHah1dLdSxfsR0usqQTxHF2dCDGMtk/HTl58M+zYesSFgBD01SWgVwrbiWUWVUhWCdgNu2qG3m9VJNiOf/xE9TAZl9CapFnrNGhkatBmD+rz7WEV8R2TRBHREpsQ31mhJJMbb1cOgRYS6XyohvCEh5W3DtQttLUFoehtJYZcNlpMi0PGDz4UTQEJpJYtL16gRVXhMUwQ+liWPqMoNOYB9ym+y8MGDLpUZ94OJUkKnbqiQ4cWGh5dDeMU=
  file: semver
  on:
    repo: davidrjonas/semver-cli
    tags: true
