[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "^1.4.0"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "^2.2.6"
